import {CPM_Graph} from './Graph'; // Dostosuj ścieżkę importu, jeśli trzeba

export const mockCpmGraph: CPM_Graph = {
    type: "AON",
    nodes: [
        {
            id: 0,
            name: 'Start Project',
            duration: 2,
            es: 0,
            ef: 2,
            ls: 0,
            lf: 2,
            critical: true,
            predecessors: [],
            successors: [{index: 1, }, {index: 2, }],
        },
        {
            id: 1,
            name: 'Task A',
            duration: 5,
            es: 2,
            ef: 7,
            ls: 2,
            lf: 7,
            critical: true,
            predecessors: [0],
            successors: [{index: 3, }],
        },
        {
            id: 2,
            name: 'Task B',
            duration: 3,
            es: 2,
            ef: 5,
            ls: 6,
            lf: 9,
            critical: false,
            predecessors: [0],
            successors: [{ index: 4, }],
        },
        {
            id: 3,
            name: 'Task C',
            duration: 4,
            es: 7,
            ef: 11,
            ls: 7,
            lf: 11,
            critical: true,
            predecessors: [1],
            successors: [{ index: 5, }],
        },
        {
            id: 4,
            name: 'Task D',
            duration: 2,
            es: 5,
            ef: 7,
            ls: 9,
            lf: 11,
            critical: false,
            predecessors: [2],
            successors: [{ index: 5, }],
        },
        {
            id: 5,
            name: 'End Project',
            duration: 0,
            es: 11,
            ef: 11,
            ls: 11,
            lf: 11,
            critical: true,
            predecessors: [3, 4],
            successors: [],
        },
    ]
};